### PR TITLE
Bumped SQLite to latest master

### PR DESCRIPTION
**Pull request by fonsocarre**

### CODE REVIEW

**Comment by mosquito** [comment]
@fonsocarre could you please remove 3.6 from actions config and add the 3.11?

**Comment by fonsocarre** [comment]
Ok, added a bunch of 3.11 and removed all the 3.6 references from `publish.yml`, `tests.yml` and `tox.ini`

**Comment by fonsocarre** [comment]
It seems I forgot one. 1 sec

**Comment by mosquito** [comment]
@fonsocarre released as https://pypi.org/project/lsm/0.4.7/

**Pull request merged**
